project:
  type: website
execute:
    freeze: auto  # This ensures code is only re-run when its specific .qmd file changes

website:
  navbar:
    left:
      - href: index.qmd
        text: home
      - href: musings.qmd
        text: musings

format:
  html:
    theme: cyborg
    page-layout: full
    toc: true
    code-fold: true
    date-format: long
    css: styles.css

